package com.android.dev.data.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.android.dev.data.db.LocationInfo;
import com.android.dev.data.db.PostInfo;

import com.android.dev.data.db.LocationInfoDao;
import com.android.dev.data.db.PostInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationInfoDaoConfig;
    private final DaoConfig postInfoDaoConfig;

    private final LocationInfoDao locationInfoDao;
    private final PostInfoDao postInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationInfoDaoConfig = daoConfigMap.get(LocationInfoDao.class).clone();
        locationInfoDaoConfig.initIdentityScope(type);

        postInfoDaoConfig = daoConfigMap.get(PostInfoDao.class).clone();
        postInfoDaoConfig.initIdentityScope(type);

        locationInfoDao = new LocationInfoDao(locationInfoDaoConfig, this);
        postInfoDao = new PostInfoDao(postInfoDaoConfig, this);

        registerDao(LocationInfo.class, locationInfoDao);
        registerDao(PostInfo.class, postInfoDao);
    }
    
    public void clear() {
        locationInfoDaoConfig.getIdentityScope().clear();
        postInfoDaoConfig.getIdentityScope().clear();
    }

    public LocationInfoDao getLocationInfoDao() {
        return locationInfoDao;
    }

    public PostInfoDao getPostInfoDao() {
        return postInfoDao;
    }

}
