package com.android.dev.data.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "POST_INFO".
 */
public class PostInfo {

    private Long id;
    private String content;
    private Integer rate;
    private Long locationId;
    private Long createTime;
    private Long updateTime;

    public PostInfo() {
    }

    public PostInfo(Long id) {
        this.id = id;
    }

    public PostInfo(Long id, String content, Integer rate, Long locationId, Long createTime, Long updateTime) {
        this.id = id;
        this.content = content;
        this.rate = rate;
        this.locationId = locationId;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getRate() {
        return rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

    public Long getLocationId() {
        return locationId;
    }

    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

}
